---

- name: install pip modules
  pip:
    name: ansible-lint
    state: present
  register: pkg_result
  until: pkg_result is success
  environment:
    ANSIBLE_SKIP_CONFLICT_CHECK: "{{ ANSIBLE_SKIP_CONFLICT_CHECK | default('0') }}"
